Repository kevocodes/practica-taller-03, pull requests merged in 2025-05, with the labels that each got.

#71 :bug: bug: solution bug in register page
  Hernández_Fabio.md
Labels: bug

#77 🐛 bug: Solucion para guardar cambios en el perfil de usuario
  Aguilar_Melvin.md
Labels: bug

#81 ✨ feat: agregando busqueda global
  Aguilar_Melvin.md
Labels: enhancement

#84 Feature/resolve issues 21
  Alas_Noe.md
Labels: enhancement

#83 Feature/resolve issue 19
  .DS_Store
  Orellana_Gerardo.md
Labels: enhancement

#90 :bug: fix: solution bug in documentation by project
  Hernández_Fabio.md
Labels: bug

#91 :bug: fix: help solving issue
  Escobar_Henry.md
Labels: bug

#93 🐛 fix: corrige bug: guardar nuevo comentario desde el formulario (fix…
  Gomez_Carlos.md
Labels: bug

#110 ✨ feat(diaz_melvin.md): agregar archivo Diaz_Melvin.md (closes #33)
  Diaz_Melvin.md
Labels: enhancement

#120 Add Markdown file Salvador Guerra
  Guerra_Salvador.md
Labels: documentation

#126 🐛 fix: Corrected pagination in gallery with active filters
  Martinez_kevin.md
Labels: bug

#133 🐛 fix: enable individual completion for recurring task instances (36)
  Leiva_Omar.md
Labels: bug

#132 ✨ feat: add content favorites functionality
  Cruz_Oscar.md
Labels: enhancement

#137 ✨ feat: upload PDF module
  Robles_Romero.md
Labels: enhancement

#138 ✨ feat: add real-time validation to profile form fields
  Huezo_Enrique.md
Labels: enhancement

#148 :bug: fix: corregir persistencia errónea de imagen de perfil
  Campos_Denys.md
Labels: bug

#149 fix: clients view filters not working
  Rivas_Michelle.md
Labels: bug

#167 Implementación del panel de administrador
  Hernández_Carlos.md
Labels: bug
